# Generated by Django 2.1.2 on 2019-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrangePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strange_value', models.BigIntegerField(default=0)),
                ('normal_face', models.ImageField(upload_to='images/normal_face/')),
                ('strange_face', models.ImageField(upload_to='images/strange_face/')),
            ],
        ),
    ]
