# Generated by Django 2.1.2 on 2019-05-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange_face', '0002_auto_20190521_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='normal_face',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='strange_face',
            field=models.ImageField(upload_to=''),
        ),
    ]
