# Generated by Django 2.1.2 on 2019-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange_face', '0004_auto_20190521_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='normal_face',
            field=models.ImageField(upload_to='normal_face/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='strange_face',
            field=models.ImageField(upload_to='strange_face/'),
        ),
    ]
