# Generated by Django 2.1.2 on 2020-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange_face', '0005_auto_20191223_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='normal_face',
            field=models.ImageField(upload_to='images/normal_face'),
        ),
        migrations.AlterField(
            model_name='person',
            name='strange_face',
            field=models.ImageField(upload_to='images/strange_face'),
        ),
    ]
