# Generated by Django 2.1.2 on 2020-01-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange_face', '0007_auto_20200105_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='normal_face',
            field=models.ImageField(blank=True, null=True, upload_to='images/normal_face/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='strange_face',
            field=models.ImageField(blank=True, null=True, upload_to='images/strange_face/'),
        ),
    ]
